name: mibi_melos

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - tests

ignore:
  - packages/**/example

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    exec: dart analyze .
