// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.10
// source: proto/system/v1/system.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallStatus string                 `protobuf:"bytes,1,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"` // HEALTHY, DEGRADED, UNHEALTHY
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Server        *ComponentStatus       `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Database      *ComponentStatus       `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Storage       *ComponentStatus       `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *HealthCheckResponse) GetServer() *ComponentStatus {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *HealthCheckResponse) GetDatabase() *ComponentStatus {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *HealthCheckResponse) GetStorage() *ComponentStatus {
	if x != nil {
		return x.Storage
	}
	return nil
}

type ComponentStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // OK, ERROR, UNAVAILABLE
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_proto_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_proto_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComponentStatus) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

var File_proto_system_v1_system_proto protoreflect.FileDescriptor

const file_proto_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/system/v1/system.proto\x12\tsystem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12HealthCheckRequest\"\x99\x02\n" +
	"\x13HealthCheckResponse\x12%\n" +
	"\x0eoverall_status\x18\x01 \x01(\tR\roverallStatus\x129\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x122\n" +
	"\x06server\x18\x03 \x01(\v2\x1a.system.v1.ComponentStatusR\x06server\x126\n" +
	"\bdatabase\x18\x04 \x01(\v2\x1a.system.v1.ComponentStatusR\bdatabase\x124\n" +
	"\astorage\x18\x05 \x01(\v2\x1a.system.v1.ComponentStatusR\astorage\"\x81\x01\n" +
	"\x0fComponentStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs2a\n" +
	"\rSystemService\x12P\n" +
	"\x0fGetHealthStatus\x12\x1d.system.v1.HealthCheckRequest\x1a\x1e.system.v1.HealthCheckResponseB>Z<github.com/mibi2007/familytree/familytree_go/proto/system/v1b\x06proto3"

var (
	file_proto_system_v1_system_proto_rawDescOnce sync.Once
	file_proto_system_v1_system_proto_rawDescData []byte
)

func file_proto_system_v1_system_proto_rawDescGZIP() []byte {
	file_proto_system_v1_system_proto_rawDescOnce.Do(func() {
		file_proto_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_v1_system_proto_rawDesc), len(file_proto_system_v1_system_proto_rawDesc)))
	})
	return file_proto_system_v1_system_proto_rawDescData
}

var file_proto_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_system_v1_system_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),    // 0: system.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 1: system.v1.HealthCheckResponse
	(*ComponentStatus)(nil),       // 2: system.v1.ComponentStatus
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_system_v1_system_proto_depIdxs = []int32{
	3, // 0: system.v1.HealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	2, // 1: system.v1.HealthCheckResponse.server:type_name -> system.v1.ComponentStatus
	2, // 2: system.v1.HealthCheckResponse.database:type_name -> system.v1.ComponentStatus
	2, // 3: system.v1.HealthCheckResponse.storage:type_name -> system.v1.ComponentStatus
	0, // 4: system.v1.SystemService.GetHealthStatus:input_type -> system.v1.HealthCheckRequest
	1, // 5: system.v1.SystemService.GetHealthStatus:output_type -> system.v1.HealthCheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_system_v1_system_proto_init() }
func file_proto_system_v1_system_proto_init() {
	if File_proto_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_v1_system_proto_rawDesc), len(file_proto_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_v1_system_proto_goTypes,
		DependencyIndexes: file_proto_system_v1_system_proto_depIdxs,
		MessageInfos:      file_proto_system_v1_system_proto_msgTypes,
	}.Build()
	File_proto_system_v1_system_proto = out.File
	file_proto_system_v1_system_proto_goTypes = nil
	file_proto_system_v1_system_proto_depIdxs = nil
}
