name: shared_package
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.2

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: 1.12.30
  flutter_animate: 4.1.1+1
  fpdart: 0.6.0
  google_fonts: 4.0.5
  hooks_riverpod: 2.3.6
  intl: 0.18.0
  flex_color_scheme: 7.1.2
  shared_preferences: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: null
  flutter_lints: 2.0.1
  freezed: 2.3.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/google_fonts/
