// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7p4XJewoqPTjK9xKqtFwNMmjdpjHRrCU',
    appId: '1:165254828005:web:302c2e3db2b4e88218e90c',
    messagingSenderId: '165254828005',
    projectId: 'mibi-family-tree',
    authDomain: 'mibi-family-tree.firebaseapp.com',
    storageBucket: 'mibi-family-tree.appspot.com',
    measurementId: 'G-G45BRDSELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI5-jfv4y--ZLduLr_dKuKbyXO58_32fw',
    appId: '1:165254828005:android:f8dc2e55c7ef914518e90c',
    messagingSenderId: '165254828005',
    projectId: 'mibi-family-tree',
    storageBucket: 'mibi-family-tree.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZph54ehCigqf7kQ20uwk3aHqrDlouek',
    appId: '1:165254828005:ios:fe554c5bec4a436118e90c',
    messagingSenderId: '165254828005',
    projectId: 'mibi-family-tree',
    storageBucket: 'mibi-family-tree.appspot.com',
    androidClientId: '165254828005-igdlcu39pqekvcgc6v0skjal3q2msj6e.apps.googleusercontent.com',
    iosClientId: '165254828005-5d41is2dfpsjfkae6adl13h8l7thiqrh.apps.googleusercontent.com',
    iosBundleId: 'com.mibi.familytree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtZph54ehCigqf7kQ20uwk3aHqrDlouek',
    appId: '1:165254828005:ios:14f1f8c86496f32a18e90c',
    messagingSenderId: '165254828005',
    projectId: 'mibi-family-tree',
    storageBucket: 'mibi-family-tree.appspot.com',
    androidClientId: '165254828005-igdlcu39pqekvcgc6v0skjal3q2msj6e.apps.googleusercontent.com',
    iosClientId: '165254828005-ccdi4bi9auvgiqu5b0sfc8jb7m983tcg.apps.googleusercontent.com',
    iosBundleId: 'com.mibi.familytree.RunnerTests',
  );
}
