// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/ai/v1/ai.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FamilyId        string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	ActingMemberId  string                 `protobuf:"bytes,2,opt,name=acting_member_id,json=actingMemberId,proto3" json:"acting_member_id,omitempty"`
	Question        string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	ConversationRef string                 `protobuf:"bytes,4,opt,name=conversation_ref,json=conversationRef,proto3" json:"conversation_ref,omitempty"`
	GroupChat       bool                   `protobuf:"varint,5,opt,name=group_chat,json=groupChat,proto3" json:"group_chat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AskRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *AskRequest) GetActingMemberId() string {
	if x != nil {
		return x.ActingMemberId
	}
	return ""
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetConversationRef() string {
	if x != nil {
		return x.ConversationRef
	}
	return ""
}

func (x *AskRequest) GetGroupChat() bool {
	if x != nil {
		return x.GroupChat
	}
	return false
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AskResponse) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

var File_proto_ai_v1_ai_proto protoreflect.FileDescriptor

const file_proto_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ai/v1/ai.proto\x12\x05ai.v1\"\xb9\x01\n" +
	"\n" +
	"AskRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12(\n" +
	"\x10acting_member_id\x18\x02 \x01(\tR\x0eactingMemberId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12)\n" +
	"\x10conversation_ref\x18\x04 \x01(\tR\x0fconversationRef\x12\x1d\n" +
	"\n" +
	"group_chat\x18\x05 \x01(\bR\tgroupChat\"W\n" +
	"\vAskResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final2o\n" +
	"\tAIService\x12,\n" +
	"\x03Ask\x12\x11.ai.v1.AskRequest\x1a\x12.ai.v1.AskResponse\x124\n" +
	"\tAskStream\x12\x11.ai.v1.AskRequest\x1a\x12.ai.v1.AskResponse0\x01B:Z8github.com/mibi2007/familytree/familytree_go/proto/ai/v1b\x06proto3"

var (
	file_proto_ai_v1_ai_proto_rawDescOnce sync.Once
	file_proto_ai_v1_ai_proto_rawDescData []byte
)

func file_proto_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_v1_ai_proto_rawDesc), len(file_proto_ai_v1_ai_proto_rawDesc)))
	})
	return file_proto_ai_v1_ai_proto_rawDescData
}

var file_proto_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ai_v1_ai_proto_goTypes = []any{
	(*AskRequest)(nil),  // 0: ai.v1.AskRequest
	(*AskResponse)(nil), // 1: ai.v1.AskResponse
}
var file_proto_ai_v1_ai_proto_depIdxs = []int32{
	0, // 0: ai.v1.AIService.Ask:input_type -> ai.v1.AskRequest
	0, // 1: ai.v1.AIService.AskStream:input_type -> ai.v1.AskRequest
	1, // 2: ai.v1.AIService.Ask:output_type -> ai.v1.AskResponse
	1, // 3: ai.v1.AIService.AskStream:output_type -> ai.v1.AskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_v1_ai_proto_init() }
func file_proto_ai_v1_ai_proto_init() {
	if File_proto_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_v1_ai_proto_rawDesc), len(file_proto_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_v1_ai_proto = out.File
	file_proto_ai_v1_ai_proto_goTypes = nil
	file_proto_ai_v1_ai_proto_depIdxs = nil
}
