// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.10
// source: proto/auth/v1/auth.proto

package v1

import (
	v1 "github.com/mibi2007/familytree/familytree_go/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPurpose int32

const (
	TokenPurpose_TOKEN_PURPOSE_UNSPECIFIED      TokenPurpose = 0
	TokenPurpose_TOKEN_PURPOSE_ADMIN_ONBOARDING TokenPurpose = 1
	TokenPurpose_TOKEN_PURPOSE_FAMILY_INVITE    TokenPurpose = 2
	TokenPurpose_TOKEN_PURPOSE_SUPPORT_GRANT    TokenPurpose = 3
)

// Enum value maps for TokenPurpose.
var (
	TokenPurpose_name = map[int32]string{
		0: "TOKEN_PURPOSE_UNSPECIFIED",
		1: "TOKEN_PURPOSE_ADMIN_ONBOARDING",
		2: "TOKEN_PURPOSE_FAMILY_INVITE",
		3: "TOKEN_PURPOSE_SUPPORT_GRANT",
	}
	TokenPurpose_value = map[string]int32{
		"TOKEN_PURPOSE_UNSPECIFIED":      0,
		"TOKEN_PURPOSE_ADMIN_ONBOARDING": 1,
		"TOKEN_PURPOSE_FAMILY_INVITE":    2,
		"TOKEN_PURPOSE_SUPPORT_GRANT":    3,
	}
)

func (x TokenPurpose) Enum() *TokenPurpose {
	p := new(TokenPurpose)
	*p = x
	return p
}

func (x TokenPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (TokenPurpose) Type() protoreflect.EnumType {
	return &file_proto_auth_v1_auth_proto_enumTypes[0]
}

func (x TokenPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenPurpose.Descriptor instead.
func (TokenPurpose) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	RequestStatus_REQUEST_STATUS_PENDING     RequestStatus = 1
	RequestStatus_REQUEST_STATUS_APPROVED    RequestStatus = 2
	RequestStatus_REQUEST_STATUS_REJECTED    RequestStatus = 3
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REQUEST_STATUS_UNSPECIFIED",
		1: "REQUEST_STATUS_PENDING",
		2: "REQUEST_STATUS_APPROVED",
		3: "REQUEST_STATUS_REJECTED",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_UNSPECIFIED": 0,
		"REQUEST_STATUS_PENDING":     1,
		"REQUEST_STATUS_APPROVED":    2,
		"REQUEST_STATUS_REJECTED":    3,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_proto_auth_v1_auth_proto_enumTypes[1]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InviteToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Purpose       TokenPurpose           `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.TokenPurpose" json:"purpose,omitempty"`
	AssociatedId  string                 `protobuf:"bytes,3,opt,name=associated_id,json=associatedId,proto3" json:"associated_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsUsed        bool                   `protobuf:"varint,5,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToken) Reset() {
	*x = InviteToken{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToken) ProtoMessage() {}

func (x *InviteToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToken.ProtoReflect.Descriptor instead.
func (*InviteToken) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *InviteToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InviteToken) GetPurpose() TokenPurpose {
	if x != nil {
		return x.Purpose
	}
	return TokenPurpose_TOKEN_PURPOSE_UNSPECIFIED
}

func (x *InviteToken) GetAssociatedId() string {
	if x != nil {
		return x.AssociatedId
	}
	return ""
}

func (x *InviteToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *InviteToken) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

type GenerateInviteTokenRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Purpose      TokenPurpose           `protobuf:"varint,1,opt,name=purpose,proto3,enum=auth.v1.TokenPurpose" json:"purpose,omitempty"`
	AssociatedId string                 `protobuf:"bytes,2,opt,name=associated_id,json=associatedId,proto3" json:"associated_id,omitempty"`
	// Expiration in seconds: 3600 (1h), 86400 (1d), 0 (unlimited)
	LifetimeSeconds int64 `protobuf:"varint,3,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateInviteTokenRequest) Reset() {
	*x = GenerateInviteTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteTokenRequest) ProtoMessage() {}

func (x *GenerateInviteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateInviteTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateInviteTokenRequest) GetPurpose() TokenPurpose {
	if x != nil {
		return x.Purpose
	}
	return TokenPurpose_TOKEN_PURPOSE_UNSPECIFIED
}

func (x *GenerateInviteTokenRequest) GetAssociatedId() string {
	if x != nil {
		return x.AssociatedId
	}
	return ""
}

func (x *GenerateInviteTokenRequest) GetLifetimeSeconds() int64 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

type ValidateInviteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInviteTokenRequest) Reset() {
	*x = ValidateInviteTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInviteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInviteTokenRequest) ProtoMessage() {}

func (x *ValidateInviteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInviteTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateInviteTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateInviteTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateInviteTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Purpose       TokenPurpose           `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.TokenPurpose" json:"purpose,omitempty"`
	AssociatedId  string                 `protobuf:"bytes,3,opt,name=associated_id,json=associatedId,proto3" json:"associated_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInviteTokenResponse) Reset() {
	*x = ValidateInviteTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInviteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInviteTokenResponse) ProtoMessage() {}

func (x *ValidateInviteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInviteTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateInviteTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateInviteTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateInviteTokenResponse) GetPurpose() TokenPurpose {
	if x != nil {
		return x.Purpose
	}
	return TokenPurpose_TOKEN_PURPOSE_UNSPECIFIED
}

func (x *ValidateInviteTokenResponse) GetAssociatedId() string {
	if x != nil {
		return x.AssociatedId
	}
	return ""
}

type RequestAdminAccessRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvitationToken string                 `protobuf:"bytes,1,opt,name=invitation_token,json=invitationToken,proto3" json:"invitation_token,omitempty"`
	RequestedRole   string                 `protobuf:"bytes,2,opt,name=requested_role,json=requestedRole,proto3" json:"requested_role,omitempty"` // e.g., "SUPER_ADMIN"
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestAdminAccessRequest) Reset() {
	*x = RequestAdminAccessRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAdminAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAdminAccessRequest) ProtoMessage() {}

func (x *RequestAdminAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAdminAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestAdminAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RequestAdminAccessRequest) GetInvitationToken() string {
	if x != nil {
		return x.InvitationToken
	}
	return ""
}

func (x *RequestAdminAccessRequest) GetRequestedRole() string {
	if x != nil {
		return x.RequestedRole
	}
	return ""
}

func (x *RequestAdminAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AdminAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestedRole string                 `protobuf:"bytes,3,opt,name=requested_role,json=requestedRole,proto3" json:"requested_role,omitempty"`
	Status        RequestStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=auth.v1.RequestStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ReviewedBy    string                 `protobuf:"bytes,6,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserProfile   *v1.UserProfile        `protobuf:"bytes,8,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAccessRequest) Reset() {
	*x = AdminAccessRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAccessRequest) ProtoMessage() {}

func (x *AdminAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAccessRequest.ProtoReflect.Descriptor instead.
func (*AdminAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AdminAccessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminAccessRequest) GetRequestedRole() string {
	if x != nil {
		return x.RequestedRole
	}
	return ""
}

func (x *AdminAccessRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *AdminAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdminAccessRequest) GetReviewedBy() string {
	if x != nil {
		return x.ReviewedBy
	}
	return ""
}

func (x *AdminAccessRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AdminAccessRequest) GetUserProfile() *v1.UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type ListAdminRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterStatus  RequestStatus          `protobuf:"varint,1,opt,name=filter_status,json=filterStatus,proto3,enum=auth.v1.RequestStatus" json:"filter_status,omitempty"`
	Pagination    *v1.PaginatedRequest   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRequestsRequest) Reset() {
	*x = ListAdminRequestsRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRequestsRequest) ProtoMessage() {}

func (x *ListAdminRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ListAdminRequestsRequest) GetFilterStatus() RequestStatus {
	if x != nil {
		return x.FilterStatus
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *ListAdminRequestsRequest) GetPagination() *v1.PaginatedRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAdminRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AdminAccessRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Pagination    *v1.PaginatedResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRequestsResponse) Reset() {
	*x = ListAdminRequestsResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRequestsResponse) ProtoMessage() {}

func (x *ListAdminRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListAdminRequestsResponse) GetRequests() []*AdminAccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListAdminRequestsResponse) GetPagination() *v1.PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReviewAdminRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision      RequestStatus          `protobuf:"varint,2,opt,name=decision,proto3,enum=auth.v1.RequestStatus" json:"decision,omitempty"` // APPROVED or REJECTED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewAdminRequestRequest) Reset() {
	*x = ReviewAdminRequestRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewAdminRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewAdminRequestRequest) ProtoMessage() {}

func (x *ReviewAdminRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewAdminRequestRequest.ProtoReflect.Descriptor instead.
func (*ReviewAdminRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ReviewAdminRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReviewAdminRequestRequest) GetDecision() RequestStatus {
	if x != nil {
		return x.Decision
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

type SyncUserProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data from Firebase JWT
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PhotoUrl      string `protobuf:"bytes,2,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserProfileRequest) Reset() {
	*x = SyncUserProfileRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserProfileRequest) ProtoMessage() {}

func (x *SyncUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserProfileRequest.ProtoReflect.Descriptor instead.
func (*SyncUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SyncUserProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SyncUserProfileRequest) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type AuthStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsSuperAdmin         bool                   `protobuf:"varint,1,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	PendingRequestStatus RequestStatus          `protobuf:"varint,2,opt,name=pending_request_status,json=pendingRequestStatus,proto3,enum=auth.v1.RequestStatus" json:"pending_request_status,omitempty"` // UNSPECIFIED if none
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthStatusResponse) Reset() {
	*x = AuthStatusResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStatusResponse) ProtoMessage() {}

func (x *AuthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStatusResponse.ProtoReflect.Descriptor instead.
func (*AuthStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *AuthStatusResponse) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *AuthStatusResponse) GetPendingRequestStatus() RequestStatus {
	if x != nil {
		return x.PendingRequestStatus
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

var File_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/auth/v1/auth.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cproto/common/v1/common.proto\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xcd\x01\n" +
	"\vInviteToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12/\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x15.auth.v1.TokenPurposeR\apurpose\x12#\n" +
	"\rassociated_id\x18\x03 \x01(\tR\fassociatedId\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x17\n" +
	"\ais_used\x18\x05 \x01(\bR\x06isUsed\"\x9d\x01\n" +
	"\x1aGenerateInviteTokenRequest\x12/\n" +
	"\apurpose\x18\x01 \x01(\x0e2\x15.auth.v1.TokenPurposeR\apurpose\x12#\n" +
	"\rassociated_id\x18\x02 \x01(\tR\fassociatedId\x12)\n" +
	"\x10lifetime_seconds\x18\x03 \x01(\x03R\x0flifetimeSeconds\"2\n" +
	"\x1aValidateInviteTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8e\x01\n" +
	"\x1bValidateInviteTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12/\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x15.auth.v1.TokenPurposeR\apurpose\x12#\n" +
	"\rassociated_id\x18\x03 \x01(\tR\fassociatedId\"\x85\x01\n" +
	"\x19RequestAdminAccessRequest\x12)\n" +
	"\x10invitation_token\x18\x01 \x01(\tR\x0finvitationToken\x12%\n" +
	"\x0erequested_role\x18\x02 \x01(\tR\rrequestedRole\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xc3\x02\n" +
	"\x12AdminAccessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0erequested_role\x18\x03 \x01(\tR\rrequestedRole\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.auth.v1.RequestStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1f\n" +
	"\vreviewed_by\x18\x06 \x01(\tR\n" +
	"reviewedBy\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\fuser_profile\x18\b \x01(\v2\x16.common.v1.UserProfileR\vuserProfile\"\x94\x01\n" +
	"\x18ListAdminRequestsRequest\x12;\n" +
	"\rfilter_status\x18\x01 \x01(\x0e2\x16.auth.v1.RequestStatusR\ffilterStatus\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.common.v1.PaginatedRequestR\n" +
	"pagination\"\x92\x01\n" +
	"\x19ListAdminRequestsResponse\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.auth.v1.AdminAccessRequestR\brequests\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginatedResponseR\n" +
	"pagination\"n\n" +
	"\x19ReviewAdminRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x16.auth.v1.RequestStatusR\bdecision\"X\n" +
	"\x16SyncUserProfileRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tphoto_url\x18\x02 \x01(\tR\bphotoUrl\"\x88\x01\n" +
	"\x12AuthStatusResponse\x12$\n" +
	"\x0eis_super_admin\x18\x01 \x01(\bR\fisSuperAdmin\x12L\n" +
	"\x16pending_request_status\x18\x02 \x01(\x0e2\x16.auth.v1.RequestStatusR\x14pendingRequestStatus*\x93\x01\n" +
	"\fTokenPurpose\x12\x1d\n" +
	"\x19TOKEN_PURPOSE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTOKEN_PURPOSE_ADMIN_ONBOARDING\x10\x01\x12\x1f\n" +
	"\x1bTOKEN_PURPOSE_FAMILY_INVITE\x10\x02\x12\x1f\n" +
	"\x1bTOKEN_PURPOSE_SUPPORT_GRANT\x10\x03*\x85\x01\n" +
	"\rRequestStatus\x12\x1e\n" +
	"\x1aREQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REQUEST_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REQUEST_STATUS_APPROVED\x10\x02\x12\x1b\n" +
	"\x17REQUEST_STATUS_REJECTED\x10\x032\xa7\x05\n" +
	"\vAuthService\x12P\n" +
	"\x13GenerateInviteToken\x12#.auth.v1.GenerateInviteTokenRequest\x1a\x14.auth.v1.InviteToken\x12`\n" +
	"\x13ValidateInviteToken\x12#.auth.v1.ValidateInviteTokenRequest\x1a$.auth.v1.ValidateInviteTokenResponse\x12U\n" +
	"\x12RequestAdminAccess\x12\".auth.v1.RequestAdminAccessRequest\x1a\x1b.auth.v1.AdminAccessRequest\x12Z\n" +
	"\x11ListAdminRequests\x12!.auth.v1.ListAdminRequestsRequest\x1a\".auth.v1.ListAdminRequestsResponse\x12U\n" +
	"\x12ReviewAdminRequest\x12\".auth.v1.ReviewAdminRequestRequest\x1a\x1b.auth.v1.AdminAccessRequest\x12J\n" +
	"\x0fSyncUserProfile\x12\x1f.auth.v1.SyncUserProfileRequest\x1a\x16.common.v1.UserProfile\x12H\n" +
	"\x0eGetUserProfile\x12\x1e.auth.v1.GetUserProfileRequest\x1a\x16.common.v1.UserProfile\x12D\n" +
	"\rGetAuthStatus\x12\x16.google.protobuf.Empty\x1a\x1b.auth.v1.AuthStatusResponseB<Z:github.com/mibi2007/familytree/familytree_go/proto/auth/v1b\x06proto3"

var (
	file_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_proto_auth_v1_auth_proto_rawDescData
}

var file_proto_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_auth_v1_auth_proto_goTypes = []any{
	(TokenPurpose)(0),                   // 0: auth.v1.TokenPurpose
	(RequestStatus)(0),                  // 1: auth.v1.RequestStatus
	(*GetUserProfileRequest)(nil),       // 2: auth.v1.GetUserProfileRequest
	(*InviteToken)(nil),                 // 3: auth.v1.InviteToken
	(*GenerateInviteTokenRequest)(nil),  // 4: auth.v1.GenerateInviteTokenRequest
	(*ValidateInviteTokenRequest)(nil),  // 5: auth.v1.ValidateInviteTokenRequest
	(*ValidateInviteTokenResponse)(nil), // 6: auth.v1.ValidateInviteTokenResponse
	(*RequestAdminAccessRequest)(nil),   // 7: auth.v1.RequestAdminAccessRequest
	(*AdminAccessRequest)(nil),          // 8: auth.v1.AdminAccessRequest
	(*ListAdminRequestsRequest)(nil),    // 9: auth.v1.ListAdminRequestsRequest
	(*ListAdminRequestsResponse)(nil),   // 10: auth.v1.ListAdminRequestsResponse
	(*ReviewAdminRequestRequest)(nil),   // 11: auth.v1.ReviewAdminRequestRequest
	(*SyncUserProfileRequest)(nil),      // 12: auth.v1.SyncUserProfileRequest
	(*AuthStatusResponse)(nil),          // 13: auth.v1.AuthStatusResponse
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*v1.UserProfile)(nil),              // 15: common.v1.UserProfile
	(*v1.PaginatedRequest)(nil),         // 16: common.v1.PaginatedRequest
	(*v1.PaginatedResponse)(nil),        // 17: common.v1.PaginatedResponse
	(*emptypb.Empty)(nil),               // 18: google.protobuf.Empty
}
var file_proto_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.InviteToken.purpose:type_name -> auth.v1.TokenPurpose
	14, // 1: auth.v1.InviteToken.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: auth.v1.GenerateInviteTokenRequest.purpose:type_name -> auth.v1.TokenPurpose
	0,  // 3: auth.v1.ValidateInviteTokenResponse.purpose:type_name -> auth.v1.TokenPurpose
	1,  // 4: auth.v1.AdminAccessRequest.status:type_name -> auth.v1.RequestStatus
	14, // 5: auth.v1.AdminAccessRequest.updated_at:type_name -> google.protobuf.Timestamp
	15, // 6: auth.v1.AdminAccessRequest.user_profile:type_name -> common.v1.UserProfile
	1,  // 7: auth.v1.ListAdminRequestsRequest.filter_status:type_name -> auth.v1.RequestStatus
	16, // 8: auth.v1.ListAdminRequestsRequest.pagination:type_name -> common.v1.PaginatedRequest
	8,  // 9: auth.v1.ListAdminRequestsResponse.requests:type_name -> auth.v1.AdminAccessRequest
	17, // 10: auth.v1.ListAdminRequestsResponse.pagination:type_name -> common.v1.PaginatedResponse
	1,  // 11: auth.v1.ReviewAdminRequestRequest.decision:type_name -> auth.v1.RequestStatus
	1,  // 12: auth.v1.AuthStatusResponse.pending_request_status:type_name -> auth.v1.RequestStatus
	4,  // 13: auth.v1.AuthService.GenerateInviteToken:input_type -> auth.v1.GenerateInviteTokenRequest
	5,  // 14: auth.v1.AuthService.ValidateInviteToken:input_type -> auth.v1.ValidateInviteTokenRequest
	7,  // 15: auth.v1.AuthService.RequestAdminAccess:input_type -> auth.v1.RequestAdminAccessRequest
	9,  // 16: auth.v1.AuthService.ListAdminRequests:input_type -> auth.v1.ListAdminRequestsRequest
	11, // 17: auth.v1.AuthService.ReviewAdminRequest:input_type -> auth.v1.ReviewAdminRequestRequest
	12, // 18: auth.v1.AuthService.SyncUserProfile:input_type -> auth.v1.SyncUserProfileRequest
	2,  // 19: auth.v1.AuthService.GetUserProfile:input_type -> auth.v1.GetUserProfileRequest
	18, // 20: auth.v1.AuthService.GetAuthStatus:input_type -> google.protobuf.Empty
	3,  // 21: auth.v1.AuthService.GenerateInviteToken:output_type -> auth.v1.InviteToken
	6,  // 22: auth.v1.AuthService.ValidateInviteToken:output_type -> auth.v1.ValidateInviteTokenResponse
	8,  // 23: auth.v1.AuthService.RequestAdminAccess:output_type -> auth.v1.AdminAccessRequest
	10, // 24: auth.v1.AuthService.ListAdminRequests:output_type -> auth.v1.ListAdminRequestsResponse
	8,  // 25: auth.v1.AuthService.ReviewAdminRequest:output_type -> auth.v1.AdminAccessRequest
	15, // 26: auth.v1.AuthService.SyncUserProfile:output_type -> common.v1.UserProfile
	15, // 27: auth.v1.AuthService.GetUserProfile:output_type -> common.v1.UserProfile
	13, // 28: auth.v1.AuthService.GetAuthStatus:output_type -> auth.v1.AuthStatusResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_auth_v1_auth_proto_init() }
func file_proto_auth_v1_auth_proto_init() {
	if File_proto_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_v1_auth_proto = out.File
	file_proto_auth_v1_auth_proto_goTypes = nil
	file_proto_auth_v1_auth_proto_depIdxs = nil
}
