// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.10
// source: proto/auth/v1/auth.proto

package v1

import (
	context "context"
	v1 "github.com/mibi2007/familytree/familytree_go/proto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GenerateInviteToken_FullMethodName = "/auth.v1.AuthService/GenerateInviteToken"
	AuthService_ValidateInviteToken_FullMethodName = "/auth.v1.AuthService/ValidateInviteToken"
	AuthService_RequestAdminAccess_FullMethodName  = "/auth.v1.AuthService/RequestAdminAccess"
	AuthService_ListAdminRequests_FullMethodName   = "/auth.v1.AuthService/ListAdminRequests"
	AuthService_ReviewAdminRequest_FullMethodName  = "/auth.v1.AuthService/ReviewAdminRequest"
	AuthService_SyncUserProfile_FullMethodName     = "/auth.v1.AuthService/SyncUserProfile"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Admin Onboarding
	GenerateInviteToken(ctx context.Context, in *GenerateInviteTokenRequest, opts ...grpc.CallOption) (*InviteToken, error)
	ValidateInviteToken(ctx context.Context, in *ValidateInviteTokenRequest, opts ...grpc.CallOption) (*ValidateInviteTokenResponse, error)
	RequestAdminAccess(ctx context.Context, in *RequestAdminAccessRequest, opts ...grpc.CallOption) (*AdminAccessRequest, error)
	// Admin Approval
	ListAdminRequests(ctx context.Context, in *ListAdminRequestsRequest, opts ...grpc.CallOption) (*ListAdminRequestsResponse, error)
	ReviewAdminRequest(ctx context.Context, in *ReviewAdminRequestRequest, opts ...grpc.CallOption) (*AdminAccessRequest, error)
	// Profile Management
	SyncUserProfile(ctx context.Context, in *SyncUserProfileRequest, opts ...grpc.CallOption) (*v1.UserProfile, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GenerateInviteToken(ctx context.Context, in *GenerateInviteTokenRequest, opts ...grpc.CallOption) (*InviteToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteToken)
	err := c.cc.Invoke(ctx, AuthService_GenerateInviteToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateInviteToken(ctx context.Context, in *ValidateInviteTokenRequest, opts ...grpc.CallOption) (*ValidateInviteTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateInviteTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateInviteToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RequestAdminAccess(ctx context.Context, in *RequestAdminAccessRequest, opts ...grpc.CallOption) (*AdminAccessRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAccessRequest)
	err := c.cc.Invoke(ctx, AuthService_RequestAdminAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListAdminRequests(ctx context.Context, in *ListAdminRequestsRequest, opts ...grpc.CallOption) (*ListAdminRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminRequestsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListAdminRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ReviewAdminRequest(ctx context.Context, in *ReviewAdminRequestRequest, opts ...grpc.CallOption) (*AdminAccessRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAccessRequest)
	err := c.cc.Invoke(ctx, AuthService_ReviewAdminRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SyncUserProfile(ctx context.Context, in *SyncUserProfileRequest, opts ...grpc.CallOption) (*v1.UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UserProfile)
	err := c.cc.Invoke(ctx, AuthService_SyncUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// Admin Onboarding
	GenerateInviteToken(context.Context, *GenerateInviteTokenRequest) (*InviteToken, error)
	ValidateInviteToken(context.Context, *ValidateInviteTokenRequest) (*ValidateInviteTokenResponse, error)
	RequestAdminAccess(context.Context, *RequestAdminAccessRequest) (*AdminAccessRequest, error)
	// Admin Approval
	ListAdminRequests(context.Context, *ListAdminRequestsRequest) (*ListAdminRequestsResponse, error)
	ReviewAdminRequest(context.Context, *ReviewAdminRequestRequest) (*AdminAccessRequest, error)
	// Profile Management
	SyncUserProfile(context.Context, *SyncUserProfileRequest) (*v1.UserProfile, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GenerateInviteToken(context.Context, *GenerateInviteTokenRequest) (*InviteToken, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateInviteToken not implemented")
}
func (UnimplementedAuthServiceServer) ValidateInviteToken(context.Context, *ValidateInviteTokenRequest) (*ValidateInviteTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateInviteToken not implemented")
}
func (UnimplementedAuthServiceServer) RequestAdminAccess(context.Context, *RequestAdminAccessRequest) (*AdminAccessRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAdminAccess not implemented")
}
func (UnimplementedAuthServiceServer) ListAdminRequests(context.Context, *ListAdminRequestsRequest) (*ListAdminRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminRequests not implemented")
}
func (UnimplementedAuthServiceServer) ReviewAdminRequest(context.Context, *ReviewAdminRequestRequest) (*AdminAccessRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewAdminRequest not implemented")
}
func (UnimplementedAuthServiceServer) SyncUserProfile(context.Context, *SyncUserProfileRequest) (*v1.UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUserProfile not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GenerateInviteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInviteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateInviteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateInviteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateInviteToken(ctx, req.(*GenerateInviteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateInviteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateInviteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateInviteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateInviteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateInviteToken(ctx, req.(*ValidateInviteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RequestAdminAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAdminAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RequestAdminAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RequestAdminAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RequestAdminAccess(ctx, req.(*RequestAdminAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListAdminRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListAdminRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListAdminRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListAdminRequests(ctx, req.(*ListAdminRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ReviewAdminRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewAdminRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ReviewAdminRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ReviewAdminRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ReviewAdminRequest(ctx, req.(*ReviewAdminRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SyncUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SyncUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SyncUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SyncUserProfile(ctx, req.(*SyncUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInviteToken",
			Handler:    _AuthService_GenerateInviteToken_Handler,
		},
		{
			MethodName: "ValidateInviteToken",
			Handler:    _AuthService_ValidateInviteToken_Handler,
		},
		{
			MethodName: "RequestAdminAccess",
			Handler:    _AuthService_RequestAdminAccess_Handler,
		},
		{
			MethodName: "ListAdminRequests",
			Handler:    _AuthService_ListAdminRequests_Handler,
		},
		{
			MethodName: "ReviewAdminRequest",
			Handler:    _AuthService_ReviewAdminRequest_Handler,
		},
		{
			MethodName: "SyncUserProfile",
			Handler:    _AuthService_SyncUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth/v1/auth.proto",
}
