// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.10
// source: proto/family/v1/family.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteToken   string                 `protobuf:"bytes,1,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinFamilyRequest) Reset() {
	*x = JoinFamilyRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFamilyRequest) ProtoMessage() {}

func (x *JoinFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFamilyRequest.ProtoReflect.Descriptor instead.
func (*JoinFamilyRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{0}
}

func (x *JoinFamilyRequest) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type Family struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId                string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AiBehaviorInstructions string                 `protobuf:"bytes,4,opt,name=ai_behavior_instructions,json=aiBehaviorInstructions,proto3" json:"ai_behavior_instructions,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_proto_family_v1_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{1}
}

func (x *Family) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Family) GetAiBehaviorInstructions() string {
	if x != nil {
		return x.AiBehaviorInstructions
	}
	return ""
}

func (x *Family) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // Format: YYYY-MM-DD
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SpouseId      string                 `protobuf:"bytes,8,opt,name=spouse_id,json=spouseId,proto3" json:"spouse_id,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Claimed user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_family_v1_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *Member) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Member) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Member) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Member) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Member) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Member) GetSpouseId() string {
	if x != nil {
		return x.SpouseId
	}
	return ""
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRequest) Reset() {
	*x = CreateFamilyRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRequest) ProtoMessage() {}

func (x *CreateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFamilyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRequest) Reset() {
	*x = GetFamilyRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRequest) ProtoMessage() {}

func (x *GetFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{4}
}

func (x *GetFamilyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFamilyOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,2,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFamilyOwnerRequest) Reset() {
	*x = UpdateFamilyOwnerRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFamilyOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFamilyOwnerRequest) ProtoMessage() {}

func (x *UpdateFamilyOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFamilyOwnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateFamilyOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFamilyOwnerRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *UpdateFamilyOwnerRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

type LeaveFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveFamilyRequest) Reset() {
	*x = LeaveFamilyRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveFamilyRequest) ProtoMessage() {}

func (x *LeaveFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveFamilyRequest.ProtoReflect.Descriptor instead.
func (*LeaveFamilyRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveFamilyRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SpouseId      string                 `protobuf:"bytes,4,opt,name=spouse_id,json=spouseId,proto3" json:"spouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{7}
}

func (x *AddMemberRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *AddMemberRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AddMemberRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *AddMemberRequest) GetSpouseId() string {
	if x != nil {
		return x.SpouseId
	}
	return ""
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type GetFamilyTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	VersionHash   string                 `protobuf:"bytes,2,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"` // For snapshot caching check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyTreeRequest) Reset() {
	*x = GetFamilyTreeRequest{}
	mi := &file_proto_family_v1_family_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyTreeRequest) ProtoMessage() {}

func (x *GetFamilyTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyTreeRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{10}
}

func (x *GetFamilyTreeRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *GetFamilyTreeRequest) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

type FamilyTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	VersionHash   string                 `protobuf:"bytes,2,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	NotModified   bool                   `protobuf:"varint,4,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyTree) Reset() {
	*x = FamilyTree{}
	mi := &file_proto_family_v1_family_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyTree) ProtoMessage() {}

func (x *FamilyTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyTree.ProtoReflect.Descriptor instead.
func (*FamilyTree) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{11}
}

func (x *FamilyTree) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *FamilyTree) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *FamilyTree) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *FamilyTree) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

type ListMyFamiliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Families      []*Family              `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFamiliesResponse) Reset() {
	*x = ListMyFamiliesResponse{}
	mi := &file_proto_family_v1_family_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFamiliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFamiliesResponse) ProtoMessage() {}

func (x *ListMyFamiliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_v1_family_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFamiliesResponse.ProtoReflect.Descriptor instead.
func (*ListMyFamiliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_family_v1_family_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyFamiliesResponse) GetFamilies() []*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

var File_proto_family_v1_family_proto protoreflect.FileDescriptor

const file_proto_family_v1_family_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/family/v1/family.proto\x12\tfamily.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\x11JoinFamilyRequest\x12!\n" +
	"\finvite_token\x18\x01 \x01(\tR\vinviteToken\"\xbc\x01\n" +
	"\x06Family\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x128\n" +
	"\x18ai_behavior_instructions\x18\x04 \x01(\tR\x16aiBehaviorInstructions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf8\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12\x1b\n" +
	"\tspouse_id\x18\b \x01(\tR\bspouseId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\")\n" +
	"\x13CreateFamilyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10GetFamilyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x18UpdateFamilyOwnerRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12 \n" +
	"\fnew_owner_id\x18\x02 \x01(\tR\n" +
	"newOwnerId\"1\n" +
	"\x12LeaveFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"\x8c\x01\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1b\n" +
	"\tspouse_id\x18\x04 \x01(\tR\bspouseId\"@\n" +
	"\x13UpdateMemberRequest\x12)\n" +
	"\x06member\x18\x01 \x01(\v2\x11.family.v1.MemberR\x06member\"2\n" +
	"\x13DeleteMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"V\n" +
	"\x14GetFamilyTreeRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12!\n" +
	"\fversion_hash\x18\x02 \x01(\tR\vversionHash\"\x9c\x01\n" +
	"\n" +
	"FamilyTree\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12!\n" +
	"\fversion_hash\x18\x02 \x01(\tR\vversionHash\x12+\n" +
	"\amembers\x18\x03 \x03(\v2\x11.family.v1.MemberR\amembers\x12!\n" +
	"\fnot_modified\x18\x04 \x01(\bR\vnotModified\"G\n" +
	"\x16ListMyFamiliesResponse\x12-\n" +
	"\bfamilies\x18\x01 \x03(\v2\x11.family.v1.FamilyR\bfamilies2\xbf\x05\n" +
	"\rFamilyService\x12A\n" +
	"\fCreateFamily\x12\x1e.family.v1.CreateFamilyRequest\x1a\x11.family.v1.Family\x12;\n" +
	"\tGetFamily\x12\x1b.family.v1.GetFamilyRequest\x1a\x11.family.v1.Family\x12K\n" +
	"\x11UpdateFamilyOwner\x12#.family.v1.UpdateFamilyOwnerRequest\x1a\x11.family.v1.Family\x12D\n" +
	"\vLeaveFamily\x12\x1d.family.v1.LeaveFamilyRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0eListMyFamilies\x12\x16.google.protobuf.Empty\x1a!.family.v1.ListMyFamiliesResponse\x12;\n" +
	"\tAddMember\x12\x1b.family.v1.AddMemberRequest\x1a\x11.family.v1.Member\x12A\n" +
	"\fUpdateMember\x12\x1e.family.v1.UpdateMemberRequest\x1a\x11.family.v1.Member\x12F\n" +
	"\fDeleteMember\x12\x1e.family.v1.DeleteMemberRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rGetFamilyTree\x12\x1f.family.v1.GetFamilyTreeRequest\x1a\x15.family.v1.FamilyTree\x12=\n" +
	"\n" +
	"JoinFamily\x12\x1c.family.v1.JoinFamilyRequest\x1a\x11.family.v1.FamilyB>Z<github.com/mibi2007/familytree/familytree_go/proto/family/v1b\x06proto3"

var (
	file_proto_family_v1_family_proto_rawDescOnce sync.Once
	file_proto_family_v1_family_proto_rawDescData []byte
)

func file_proto_family_v1_family_proto_rawDescGZIP() []byte {
	file_proto_family_v1_family_proto_rawDescOnce.Do(func() {
		file_proto_family_v1_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_family_v1_family_proto_rawDesc), len(file_proto_family_v1_family_proto_rawDesc)))
	})
	return file_proto_family_v1_family_proto_rawDescData
}

var file_proto_family_v1_family_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_family_v1_family_proto_goTypes = []any{
	(*JoinFamilyRequest)(nil),        // 0: family.v1.JoinFamilyRequest
	(*Family)(nil),                   // 1: family.v1.Family
	(*Member)(nil),                   // 2: family.v1.Member
	(*CreateFamilyRequest)(nil),      // 3: family.v1.CreateFamilyRequest
	(*GetFamilyRequest)(nil),         // 4: family.v1.GetFamilyRequest
	(*UpdateFamilyOwnerRequest)(nil), // 5: family.v1.UpdateFamilyOwnerRequest
	(*LeaveFamilyRequest)(nil),       // 6: family.v1.LeaveFamilyRequest
	(*AddMemberRequest)(nil),         // 7: family.v1.AddMemberRequest
	(*UpdateMemberRequest)(nil),      // 8: family.v1.UpdateMemberRequest
	(*DeleteMemberRequest)(nil),      // 9: family.v1.DeleteMemberRequest
	(*GetFamilyTreeRequest)(nil),     // 10: family.v1.GetFamilyTreeRequest
	(*FamilyTree)(nil),               // 11: family.v1.FamilyTree
	(*ListMyFamiliesResponse)(nil),   // 12: family.v1.ListMyFamiliesResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_proto_family_v1_family_proto_depIdxs = []int32{
	13, // 0: family.v1.Family.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: family.v1.UpdateMemberRequest.member:type_name -> family.v1.Member
	2,  // 2: family.v1.FamilyTree.members:type_name -> family.v1.Member
	1,  // 3: family.v1.ListMyFamiliesResponse.families:type_name -> family.v1.Family
	3,  // 4: family.v1.FamilyService.CreateFamily:input_type -> family.v1.CreateFamilyRequest
	4,  // 5: family.v1.FamilyService.GetFamily:input_type -> family.v1.GetFamilyRequest
	5,  // 6: family.v1.FamilyService.UpdateFamilyOwner:input_type -> family.v1.UpdateFamilyOwnerRequest
	6,  // 7: family.v1.FamilyService.LeaveFamily:input_type -> family.v1.LeaveFamilyRequest
	14, // 8: family.v1.FamilyService.ListMyFamilies:input_type -> google.protobuf.Empty
	7,  // 9: family.v1.FamilyService.AddMember:input_type -> family.v1.AddMemberRequest
	8,  // 10: family.v1.FamilyService.UpdateMember:input_type -> family.v1.UpdateMemberRequest
	9,  // 11: family.v1.FamilyService.DeleteMember:input_type -> family.v1.DeleteMemberRequest
	10, // 12: family.v1.FamilyService.GetFamilyTree:input_type -> family.v1.GetFamilyTreeRequest
	0,  // 13: family.v1.FamilyService.JoinFamily:input_type -> family.v1.JoinFamilyRequest
	1,  // 14: family.v1.FamilyService.CreateFamily:output_type -> family.v1.Family
	1,  // 15: family.v1.FamilyService.GetFamily:output_type -> family.v1.Family
	1,  // 16: family.v1.FamilyService.UpdateFamilyOwner:output_type -> family.v1.Family
	14, // 17: family.v1.FamilyService.LeaveFamily:output_type -> google.protobuf.Empty
	12, // 18: family.v1.FamilyService.ListMyFamilies:output_type -> family.v1.ListMyFamiliesResponse
	2,  // 19: family.v1.FamilyService.AddMember:output_type -> family.v1.Member
	2,  // 20: family.v1.FamilyService.UpdateMember:output_type -> family.v1.Member
	14, // 21: family.v1.FamilyService.DeleteMember:output_type -> google.protobuf.Empty
	11, // 22: family.v1.FamilyService.GetFamilyTree:output_type -> family.v1.FamilyTree
	1,  // 23: family.v1.FamilyService.JoinFamily:output_type -> family.v1.Family
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_family_v1_family_proto_init() }
func file_proto_family_v1_family_proto_init() {
	if File_proto_family_v1_family_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_family_v1_family_proto_rawDesc), len(file_proto_family_v1_family_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_family_v1_family_proto_goTypes,
		DependencyIndexes: file_proto_family_v1_family_proto_depIdxs,
		MessageInfos:      file_proto_family_v1_family_proto_msgTypes,
	}.Build()
	File_proto_family_v1_family_proto = out.File
	file_proto_family_v1_family_proto_goTypes = nil
	file_proto_family_v1_family_proto_depIdxs = nil
}
