// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.10
// source: proto/family/v1/family.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FamilyService_CreateFamily_FullMethodName      = "/family.v1.FamilyService/CreateFamily"
	FamilyService_GetFamily_FullMethodName         = "/family.v1.FamilyService/GetFamily"
	FamilyService_UpdateFamilyOwner_FullMethodName = "/family.v1.FamilyService/UpdateFamilyOwner"
	FamilyService_LeaveFamily_FullMethodName       = "/family.v1.FamilyService/LeaveFamily"
	FamilyService_ListMyFamilies_FullMethodName    = "/family.v1.FamilyService/ListMyFamilies"
	FamilyService_AddMember_FullMethodName         = "/family.v1.FamilyService/AddMember"
	FamilyService_UpdateMember_FullMethodName      = "/family.v1.FamilyService/UpdateMember"
	FamilyService_DeleteMember_FullMethodName      = "/family.v1.FamilyService/DeleteMember"
	FamilyService_GetFamilyTree_FullMethodName     = "/family.v1.FamilyService/GetFamilyTree"
	FamilyService_JoinFamily_FullMethodName        = "/family.v1.FamilyService/JoinFamily"
)

// FamilyServiceClient is the client API for FamilyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FamilyServiceClient interface {
	// Family Management
	CreateFamily(ctx context.Context, in *CreateFamilyRequest, opts ...grpc.CallOption) (*Family, error)
	GetFamily(ctx context.Context, in *GetFamilyRequest, opts ...grpc.CallOption) (*Family, error)
	UpdateFamilyOwner(ctx context.Context, in *UpdateFamilyOwnerRequest, opts ...grpc.CallOption) (*Family, error)
	LeaveFamily(ctx context.Context, in *LeaveFamilyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListMyFamilies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMyFamiliesResponse, error)
	// Member Management
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*Member, error)
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*Member, error)
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Tree Sync
	GetFamilyTree(ctx context.Context, in *GetFamilyTreeRequest, opts ...grpc.CallOption) (*FamilyTree, error)
	JoinFamily(ctx context.Context, in *JoinFamilyRequest, opts ...grpc.CallOption) (*Family, error)
}

type familyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFamilyServiceClient(cc grpc.ClientConnInterface) FamilyServiceClient {
	return &familyServiceClient{cc}
}

func (c *familyServiceClient) CreateFamily(ctx context.Context, in *CreateFamilyRequest, opts ...grpc.CallOption) (*Family, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Family)
	err := c.cc.Invoke(ctx, FamilyService_CreateFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GetFamily(ctx context.Context, in *GetFamilyRequest, opts ...grpc.CallOption) (*Family, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Family)
	err := c.cc.Invoke(ctx, FamilyService_GetFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) UpdateFamilyOwner(ctx context.Context, in *UpdateFamilyOwnerRequest, opts ...grpc.CallOption) (*Family, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Family)
	err := c.cc.Invoke(ctx, FamilyService_UpdateFamilyOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) LeaveFamily(ctx context.Context, in *LeaveFamilyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FamilyService_LeaveFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) ListMyFamilies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMyFamiliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyFamiliesResponse)
	err := c.cc.Invoke(ctx, FamilyService_ListMyFamilies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*Member, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Member)
	err := c.cc.Invoke(ctx, FamilyService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*Member, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Member)
	err := c.cc.Invoke(ctx, FamilyService_UpdateMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FamilyService_DeleteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GetFamilyTree(ctx context.Context, in *GetFamilyTreeRequest, opts ...grpc.CallOption) (*FamilyTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FamilyTree)
	err := c.cc.Invoke(ctx, FamilyService_GetFamilyTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) JoinFamily(ctx context.Context, in *JoinFamilyRequest, opts ...grpc.CallOption) (*Family, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Family)
	err := c.cc.Invoke(ctx, FamilyService_JoinFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FamilyServiceServer is the server API for FamilyService service.
// All implementations must embed UnimplementedFamilyServiceServer
// for forward compatibility.
type FamilyServiceServer interface {
	// Family Management
	CreateFamily(context.Context, *CreateFamilyRequest) (*Family, error)
	GetFamily(context.Context, *GetFamilyRequest) (*Family, error)
	UpdateFamilyOwner(context.Context, *UpdateFamilyOwnerRequest) (*Family, error)
	LeaveFamily(context.Context, *LeaveFamilyRequest) (*emptypb.Empty, error)
	ListMyFamilies(context.Context, *emptypb.Empty) (*ListMyFamiliesResponse, error)
	// Member Management
	AddMember(context.Context, *AddMemberRequest) (*Member, error)
	UpdateMember(context.Context, *UpdateMemberRequest) (*Member, error)
	DeleteMember(context.Context, *DeleteMemberRequest) (*emptypb.Empty, error)
	// Tree Sync
	GetFamilyTree(context.Context, *GetFamilyTreeRequest) (*FamilyTree, error)
	JoinFamily(context.Context, *JoinFamilyRequest) (*Family, error)
	mustEmbedUnimplementedFamilyServiceServer()
}

// UnimplementedFamilyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFamilyServiceServer struct{}

func (UnimplementedFamilyServiceServer) CreateFamily(context.Context, *CreateFamilyRequest) (*Family, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFamily not implemented")
}
func (UnimplementedFamilyServiceServer) GetFamily(context.Context, *GetFamilyRequest) (*Family, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFamily not implemented")
}
func (UnimplementedFamilyServiceServer) UpdateFamilyOwner(context.Context, *UpdateFamilyOwnerRequest) (*Family, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFamilyOwner not implemented")
}
func (UnimplementedFamilyServiceServer) LeaveFamily(context.Context, *LeaveFamilyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveFamily not implemented")
}
func (UnimplementedFamilyServiceServer) ListMyFamilies(context.Context, *emptypb.Empty) (*ListMyFamiliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyFamilies not implemented")
}
func (UnimplementedFamilyServiceServer) AddMember(context.Context, *AddMemberRequest) (*Member, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedFamilyServiceServer) UpdateMember(context.Context, *UpdateMemberRequest) (*Member, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMember not implemented")
}
func (UnimplementedFamilyServiceServer) DeleteMember(context.Context, *DeleteMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMember not implemented")
}
func (UnimplementedFamilyServiceServer) GetFamilyTree(context.Context, *GetFamilyTreeRequest) (*FamilyTree, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFamilyTree not implemented")
}
func (UnimplementedFamilyServiceServer) JoinFamily(context.Context, *JoinFamilyRequest) (*Family, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinFamily not implemented")
}
func (UnimplementedFamilyServiceServer) mustEmbedUnimplementedFamilyServiceServer() {}
func (UnimplementedFamilyServiceServer) testEmbeddedByValue()                       {}

// UnsafeFamilyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FamilyServiceServer will
// result in compilation errors.
type UnsafeFamilyServiceServer interface {
	mustEmbedUnimplementedFamilyServiceServer()
}

func RegisterFamilyServiceServer(s grpc.ServiceRegistrar, srv FamilyServiceServer) {
	// If the following call panics, it indicates UnimplementedFamilyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FamilyService_ServiceDesc, srv)
}

func _FamilyService_CreateFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).CreateFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_CreateFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).CreateFamily(ctx, req.(*CreateFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GetFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GetFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetFamily(ctx, req.(*GetFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_UpdateFamilyOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFamilyOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).UpdateFamilyOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_UpdateFamilyOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).UpdateFamilyOwner(ctx, req.(*UpdateFamilyOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_LeaveFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).LeaveFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_LeaveFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).LeaveFamily(ctx, req.(*LeaveFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_ListMyFamilies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).ListMyFamilies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_ListMyFamilies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).ListMyFamilies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_UpdateMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).UpdateMember(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_DeleteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).DeleteMember(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GetFamilyTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFamilyTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetFamilyTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GetFamilyTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetFamilyTree(ctx, req.(*GetFamilyTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_JoinFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).JoinFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_JoinFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).JoinFamily(ctx, req.(*JoinFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FamilyService_ServiceDesc is the grpc.ServiceDesc for FamilyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FamilyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "family.v1.FamilyService",
	HandlerType: (*FamilyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFamily",
			Handler:    _FamilyService_CreateFamily_Handler,
		},
		{
			MethodName: "GetFamily",
			Handler:    _FamilyService_GetFamily_Handler,
		},
		{
			MethodName: "UpdateFamilyOwner",
			Handler:    _FamilyService_UpdateFamilyOwner_Handler,
		},
		{
			MethodName: "LeaveFamily",
			Handler:    _FamilyService_LeaveFamily_Handler,
		},
		{
			MethodName: "ListMyFamilies",
			Handler:    _FamilyService_ListMyFamilies_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _FamilyService_AddMember_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _FamilyService_UpdateMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _FamilyService_DeleteMember_Handler,
		},
		{
			MethodName: "GetFamilyTree",
			Handler:    _FamilyService_GetFamilyTree_Handler,
		},
		{
			MethodName: "JoinFamily",
			Handler:    _FamilyService_JoinFamily_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/family/v1/family.proto",
}
