name: family_tree_chat

packages:
  - apps/**
  - packages/**

scripts:
  bootstrap:
    description: Bootstrap all packages.
    steps:
      - melos exec --scope="shared_package" -- "flutter pub get"
      - melos exec --ignore="shared_package" -- "flutter pub get"
  
  clean:
    exec: flutter clean
    description: Clean all packages.

  generate:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Generate code for all packages.

  run:admin:local:
    exec: flutter run -d web-server --web-port 8081 -t lib/main_local.dart
    packageFilters:
      scope: admin_app
    description: Run Admin App locally on port 8081
