name: familytree
description: Family Tree app uses Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_package:
    path: ../shared_package

  another_flushbar: 1.12.30
  cloud_firestore: 4.7.1
  dartz: 0.10.1
  dio: 5.1.2
  fimber: 0.6.6
  firebase_analytics: 10.4.1
  firebase_analytics_web: 0.5.4+1
  firebase_auth: 4.6.1
  firebase_core: 2.13.0
  flutter_animate: 4.1.1+1
  flutter_hooks: 0.18.6
  flutter_svg: 2.0.6
  fpdart: 0.6.0
  freezed_annotation: 2.2.0
  go_router: 7.1.1
  google_fonts: 4.0.5
  hooks_riverpod: 2.3.6
  intl: 0.18.0
  json_annotation: 4.8.1
  logging: 1.2.0
  riverpod_annotation: 2.1.1
  scrollable_positioned_list: 0.3.8
  shared_preferences: 2.1.1
  url_launcher: 6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: 2.0.1
  freezed: 2.3.4
  json_serializable: 6.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - config/
